base_link:
  sensor_kit_base_link:
    x: 1.502352 # Wall calibrator
    y: -0.047509 # Wall calibrator
    z: 1.481732681 # Ground plane calibrator
    roll: 3.121546 # Wall calibrator
    pitch: 3.029417 # Wall calibrator
    yaw: 3.050477 # Wall calibrator

  # gnss_link: # aka imu_link
  #   x: 1.506
  #   y: -0.011
  #   z: 1.2392
  #   roll: 0
  #   pitch: 0
  #   yaw: 0