base_link:
  sensor_kit_base_link:
    x: 2.3 # Estimated
    y: 0.0 # N/A
    z: 1.174232680995941 # Ground plane calibrator
    roll: 0.005707076062172211 # Ground plane calibrator
    pitch: 0.12350831632256132 # Ground plane calibrator
    yaw: -0.09 # Estimated

  gnss_link: # aka imu_link
    x: 2.306
    y: -0.011
    z: 1.6467
    roll: 0
    pitch: 0
    yaw: 0